### ISSUE TITLE
Latitude / Longitude issue

### ISSUE THREAD

**Issue by Vincentv92** [longitude-one/doctrine-spatial#19]
I think I found a very confusing bug which is easy to replicate:

Test script
```php
$lat = 52.092876;
$lon = 5.104480;
var_dump($lat, $lon);
$point = new \LongitudeOne\Spatial\PHP\Types\Geometry\Point($lat, $lon);
var_dump($point->getLatitude(), $point->getLongitude());
```

Outputs
```
float(52.092876)
float(5.10448)
float(5.10448)
float(52.092876)
```

https://github.com/longitude-one/doctrine-spatial/blob/main/lib/LongitudeOne/Spatial/PHP/Types/AbstractPoint.php#L202
Refers as Lat Lon construct (in this order) and writes lat to X and lon to Y

This is the issue:
When using `getLatitude()` it will return the data from Y instead of X. https://github.com/longitude-one/doctrine-spatial/blob/main/lib/LongitudeOne/Spatial/PHP/Types/AbstractPoint.php#L65

Would changing the getLatitude and getLongitude fix it entirely or is there unintended side effects for this?

**Comment by Alexandre-T** [comment]
I had to check this, but I encountered a lot of problems with this. 

In any case this bug will be solved in next major version. In version 3.1 using parameters in constructor will throw deprecations and it will throw errors in next major version.
So, in next major version, you will have to use:
```
$lat = 52.092876;
$lon = 5.104480;
var_dump($lat, $lon);
$point = new \LongitudeOne\Spatial\PHP\Types\Geometry\Point();
$point->setLongitude($lon);
$point->setLatitude($lat);
var_dump($point->getLatitude(), $point->getLongitude());
```

**Comment by Alexandre-T** [comment]
I read a lot of documentation, I see some disagreement here :) . Two choices to pick - too many! 

So I changed my opinion. Some users told me that the Entity model (constructors without parameters) isn't fluent.

1. I publish the 3.0.1 version
2. I fix the bug and the system to latitude/longitude by default, because ISO 6709 and because a lot of healthy services declares latitude then longitude.
3. I create a static variable which declare the order XY or YX and documented it.
4. I publish the 3.0.2 version
5. Code using more than 2 parameters in point will be deprecated (version 3.1)
6. 3 parameters on point will throw an error (version 4.0)
7. Implementation of 3D points
8. Implementation of 2DM points
9. Implementation of 3DM points
