### ISSUE TITLE
Add support for doctrine/orm 3.0

### ISSUE THREAD

**Issue by captain-igloo** [longitude-one/doctrine-spatial#43]
doctrine/orm 3.0 was released a few days ago.  Would it be possible to add support for this?

Thanks

**Comment by Alexandre-T** [comment]
I am currently forking and updating libraries (`geo-parser` and `wkt-parser`) required to migrate to `doctrine/lexer:3`. The goal is to make doctrine-spatial compatible with `doctrine/orm:3`.

**Comment by lukena-xxl** [comment]
Hello. When can we expect support for "doctrine/orm 3.1"? Thank you

**Comment by Alexandre-T** [comment]
I don't know. I am a volunteer, doing this in my spare time, and I haven't yet studied the impact between doctrine:orm 2.0 and doctrine:orm 3.0, let alone Doctrine 3.1.

**Comment by Alexandre-T** [comment]
longitude/geo-parser is done.
Todo : 
 * longitude-one/wkt-parser 
 * doctrine/orm:3

**Comment by Alexandre-T** [comment]
* `longitude-one/geo-parser` is upgraded. A pre-release 3.0.0.RC is published, it's compatible with `doctrine/lexer:3.0`
* `longitude-one/wkt-parser` is upgraded. A pre-release 3.0.0.RC is published, it's compatible with `doctrine/lexer:3.0` (and experimental 3.1)

I can now focus on `longitude-one/doctrine-spatial`

Todo :
* Fix deprecations on `longitude-one/doctrine-spatial` with the last versions `doctrine/orm:2.*` (2.19.3 today)
* Upgrade `longitude-one/doctrine-spatial` to be compliant with the last versions of `doctrine/orm:3.1.*` (3.1.1 today)
* Have a look on `doctrine/orm:3.2`
* Have a look on `doctrine/orm:4.0`

**Comment by remy-theroux** [comment]
thanks for your time

**Comment by danielgwood** [comment]
Thanks for your time. If you have a Ko-fi or similar I'd love to make a donation, it's a helpful package.

**Comment by Alexandre-T** [comment]
> Thanks for your time. If you have a Ko-fi or similar I'd love to make a donation, it's a helpful package.

Thank you very much @danielgwood : ko-fi.com/alexandret

* `longitude-one/geo-parser` is upgraded. A pre-release 3.0.0.RC is published, it's compatible with `doctrine/lexer:3.0`
* `longitude-one/wkt-parser` is upgraded. A pre-release 3.0.0.RC is published, it's compatible with `doctrine/lexer:3.0` (and experimental 3.1)
* `longitude-one/wkb-parser` is upgraded. A pre-release 3.0.0.RC is published (no dependencies)

All CrEOF libraries have been replaced (thanks for their initial work) by the longitude-one ones.
I now focus on `longitude-one/doctrine-spatial`. The [doctrine3-feature branch](https://github.com/longitude-one/doctrine-spatial/tree/doctrine3-feature) is pushed. The [CI](https://github.com/longitude-one/doctrine-spatial/actions/runs/8637082601) is working! A lot of deprecation are thrown as expected, but it will help me to fix everything!

Todo :
* ~~Fork `creof/wkb-parser`~~
* ~~Upgrade `longitude-one/wkb-parser`~~
* Fix deprecations on `longitude-one/doctrine-spatial` with the last versions of longitude-one/*parser libraries
* Fix deprecations on `longitude-one/doctrine-spatial` with the last versions `doctrine/orm:2.*` (2.19.3 today)
* Upgrade `longitude-one/doctrine-spatial` to be compliant with the last versions of `doctrine/orm:3.1.*` (3.1.1 today)
* Have a look on `doctrine/orm:3.2`
* Have a look on `doctrine/orm:4.0`

**Comment by Alexandre-T** [comment]
I'm about to create a pull request on the `dev` branch, targeting a merge with main. This will release `longitude-one:doctrine-spatial/4.1.0`. This version remains "only" compatible with `doctrine/orm:2.19`.

This weekend, I'll update the code to trigger deprecations when using MySQL 5.7. Subsequently, I'll publish `longitude-one:doctrine-spatial/4.1.1`.

### Good News! 

* I've made significant progress! Because the version 4.1.1 is already compatible with `doctrine/orm:3.0`, and all tests are passing successfully. I only have to update the `composer.json`. (ie: I already did the job 🎉​🎉​ )
* The three dependencies, `longitude-one/*-parser:3.0.0.RC`, are working flawlessly. I plan to publish them as version 3.0.0 this weekend.
* Following that, I'll focus on compatibility with `doctrine/orm:3.1`. In my estimation, this should only take a few hours of development.
* Once compatibility is achieved, I'll be able to publish `longitude-one:doctrine-spatial/5.0.0.beta`.
* Afterward, MySQL 5.7 support will be removed.
* Finally, I'll publish `longitude-one:doctrine-spatial/5.0.0.RC`.

### Target Release Date:

Based on my progress, I'm confident I can publish the 5.0.0 release candidate version by May 14th.
The final release will depend on your feedbacks.

**Comment by remy-theroux** [comment]
Good job, thank you that we encourage us to migrate to doctrine 3 ;-)

**Comment by manaka02** [comment]
Thank you very much !!

**Comment by tiapnn** [comment]
Cheers 🍻

**Comment by Alexandre-T** [comment]
Thank you for your messages.  Thanks for your messages! Don't hesitate to give me feedback on the migration process for your applications. My demo application migrated without errors, but I only use a limited portion of the library and just the PostgreSQL engine.

**Comment by captain-igloo** [comment]
Thanks for your work on this.  I have found:

* the 5.0.0.RC release still depends on doctrine/orm 2
* AbstractPoint.php has ["TODO remove this line in version 5"](https://github.com/longitude-one/doctrine-spatial/blob/dev/lib/LongitudeOne/Spatial/PHP/Types/AbstractPoint.php#L149)
* Previously longitude-one/wkt-parser returned float, now returns string, eg:

```
$parser = new \LongitudeOne\Geo\WKT\Parser();
$point = $parser->parse('POINT(174 -39.1)');
```

$point['value'][1] should be float but is now a string "-39.1"

**Comment by remy-theroux** [comment]
> Thanks for your work on this. I have found:
> 
>     * the 5.0.0.RC release still depends on doctrine/orm 2
> 
>     * AbstractPoint.php has ["TODO remove this line in version 5"](https://github.com/longitude-one/doctrine-spatial/blob/dev/lib/LongitudeOne/Spatial/PHP/Types/AbstractPoint.php#L149)
> 
>     * Previously longitude-one/wkt-parser returned float, now returns string, eg:
> 
> 
> ```
> $parser = new \LongitudeOne\Geo\WKT\Parser();
> $point = $parser->parse('POINT(174 -39.1)');
> ```
> 
> $point['value'][1] should be float but is now a string "-39.1"
The migration is available on this branch dev-doctrine3-feature

**Comment by remy-theroux** [comment]
Was available, seems to be on dev branch now.

**Comment by Alexandre-T** [comment]
Thank you, for your feedbacks @captain-igloo !

>     * AbstractPoint.php has ["TODO remove this line in version 5"](https://github.com/longitude-one/doctrine-spatial/blob/dev/lib/LongitudeOne/Spatial/PHP/Types/AbstractPoint.php#L149)
I created the issue #57 about AbstractPoint. My bad! :-) I will fix it tomorrow.

>     * Previously longitude-one/wkt-parser returned float, now returns string, eg:
> 
> 
> ```
> $parser = new \LongitudeOne\Geo\WKT\Parser();
> $point = $parser->parse('POINT(174 -39.1)');
> ```
> 
> $point['value'][1] should be float but is now a string "-39.1"

About the wkt-parser, Yes, it returns no longer float, but string. Because the doctrine/lexer only accepts string as input, I had to update the CrEOF code. And I got a lot of conversion issues when I convert it internally. Latitudes like 42.66 could become 42.67 or 42.65!!!! So, I readproof lexer and postgis manuals and the advices was to avoid float and used decimal or strings.  Why? Because the wkt-parser nor the doctrine-spatial librairies deals operations on

> Thanks for your work on this. I have found:
> 
>     * the 5.0.0.RC release still depends on doctrine/orm 2

Yes, version 5.0.0 is still compatible with doctrine/orm:^2.19. The [composer.json](https://github.com/longitude-one/doctrine-spatial/blob/23c7e7f7f7fc1af9cd59183b747d0015d78cfd90/composer.json#L32) file allows it, and unlike AbstractPoint, this is not an oversight on my part. To my surprise, my tests revealed that the code worked with both versions almost flawlessly. I applied one or two changes and the code is compatible with all versions, from 2.19 to 4.0! To ensure that this does not change over time, I have added a [matrix](https://github.com/longitude-one/doctrine-spatial/blob/23c7e7f7f7fc1af9cd59183b747d0015d78cfd90/.github/workflows/full.yaml#L19) to [change the orm](https://github.com/longitude-one/doctrine-spatial/blob/23c7e7f7f7fc1af9cd59183b747d0015d78cfd90/.github/workflows/full.yaml#L88) in the actions.

I believe that a team that wants to stay on version orm:2.19 can use version 4doctrine-spatial:4 . A team that plans to upgrade can go to 5. This allows the team not to change everything at once.

**Comment by Alexandre-T** [comment]
If no issues are reported, `longitude-one/doctrine-spatial:5.0.0` will be release on May 15th

**Comment by Alexandre-T** [comment]
https://github.com/longitude-one/doctrine-spatial/discussions/69

**Comment by captain-igloo** [comment]
Further to your comment about floats changing to strings above.  Now LongitudeOne\Spatial\PHP\Types\AbstractPoint::setX() and setY() take a string.  Should these not take int or string?

https://github.com/longitude-one/doctrine-spatial/blob/main/lib/LongitudeOne/Spatial/PHP/Types/AbstractPoint.php#L127

**Comment by Alexandre-T** [comment]
Thank you for your feedback. 

I would advise against implicitly converting integers to strings in class methods. While it may seem convenient at first glance, it can lead to several issues:
* Reduced code readability: Implicit conversion makes the code less readable and harder to understand for other developers who need to read and maintain it. It's not obvious what's happening without carefully reading the documentation or source code. 
* Violates the least surprise principle: In general, it's better to follow the least surprise principle by writing code that behaves as one expects it to. If a developer passes an integer to a method, they should expect the integer to be used as an integer, not converted to a string.
* Unexpected behavior: It can lead to unexpected errors if the developer doesn't expect the conversion. For instance, if the method uses functions expecting strings, it could result in type errors or unintended results. I agree that converting an integer to a string will have no impact, unlike floating-point numbers. But, what about the getter? Should it return string or int|string? Currently it returns string, the property `$this->x` is a string, because parser only returns string. Should I skip the parser if $x parameter is a string? It could be more efficient, but less readable. In my opinion, the `geo-parser` parse $x and returns a string. If `doctrine-spatial` skips the `geo-parser` when parameter is an integer, it's more efficient, but it violates the separation of concerns principle. (I'm not sure of the expression, I mean: _It breaks down the separation of layers, it blurs the lines between different responsibilities._

Alternatives: 
* Class isn't final, so you can overload the setter.
* You may (perhaps) use the  `declare(strict_types=0);` in your application.
* In any case, in my humble opinion, your points and mines are valid and deserve further discussion. I propose creating an issue on this topic to gain more visibility and allow us to discuss this point. This ticket is closed, and I am afraid that no one other than those notified will read it.
